package com.aeromaintenance.ai.ui.screens

import androidx.compose.animation.animateContentSize
import androidx.compose.foundation.background
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.IntrinsicSize
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxHeight
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.lazy.rememberLazyListState
import androidx.compose.foundation.rememberScrollState
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Check
import androidx.compose.material.icons.filled.Flight
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import com.aeromaintenance.ai.AeroViewModel
import com.aeromaintenance.ai.Screen
import com.aeromaintenance.ai.data.Alert
import com.aeromaintenance.ai.data.Severity
import com.aeromaintenance.ai.ui.components.Panel
import com.aeromaintenance.ai.ui.components.PrototypeNote
import com.aeromaintenance.ai.ui.components.SecondaryButton
import com.aeromaintenance.ai.ui.components.Tag
import com.aeromaintenance.ai.ui.theme.Aero
import com.aeromaintenance.ai.ui.theme.severityColor

@Composable
fun AlertsScreen(vm: AeroViewModel, padding: PaddingValues) {
    var filter by rememberSaveable { mutableStateOf<String?>(null) }
    val shown = vm.alerts.filter { filter == null || it.severity.name == filter }
    val listState = rememberLazyListState()
    LaunchedEffect(vm.demoFocus) { if (vm.demoFocus == "alert") listState.animateScrollToItem(0) }

    LazyColumn(
        Modifier.fillMaxSize(),
        state = listState,
        contentPadding = withScreenPadding(padding),
        verticalArrangement = Arrangement.spacedBy(12.dp),
    ) {
        item("filters") {
            Row(Modifier.horizontalScroll(rememberScrollState()), horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                FilterPill("All ${vm.alerts.size}", filter == null, Aero.Cyan) { filter = null }
                Severity.entries.forEach { s ->
                    FilterPill("${s.label.lowercase().replaceFirstChar { it.uppercase() }} ${vm.alerts.count { it.severity == s }}", filter == s.name, severityColor(s)) { filter = s.name }
                }
            }
        }
        if (shown.isEmpty()) {
            item("empty") {
                Text("No alerts at this severity. Run an AI analysis on abnormal data to raise one.", style = MaterialTheme.typography.bodyMedium, color = Aero.TextMuted)
            }
        }
        items(shown, key = { it.id }) { a ->
            AlertCard(
                a,
                expanded = vm.expandedAlertId == a.id,
                highlight = vm.demoFocus == "alert" && a.isNew && a.id == vm.alerts.firstOrNull()?.id,
                onToggle = { vm.expandedAlertId = if (vm.expandedAlertId == a.id) null else a.id },
                onAcknowledge = { vm.acknowledge(a.id) },
                onOpenAircraft = { vm.selectAircraft(a.aircraftId); vm.navigate(Screen.AircraftDetail(a.aircraftId)) },
            )
        }
        item("note") {
            PrototypeNote("Alerts are generated by the prototype from simulated telemetry. Explanations are produced from the analysis features, not written by hand.")
        }
    }
}

@Composable
private fun AlertCard(
    a: Alert,
    expanded: Boolean,
    highlight: Boolean,
    onToggle: () -> Unit,
    onAcknowledge: () -> Unit,
    onOpenAircraft: () -> Unit,
) {
    val color = severityColor(a.severity)
    Panel(highlight = highlight, contentPadding = 0.dp, onClick = onToggle) {
        Row(Modifier.height(IntrinsicSize.Min).animateContentSize()) {
            Box(Modifier.width(5.dp).fillMaxHeight().background(if (a.acknowledged) Aero.Hairline else color))
            Column(Modifier.weight(1f).padding(14.dp)) {
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Tag(a.severity.label, color, filled = !a.acknowledged)
                    if (a.isNew) {
                        Spacer(Modifier.width(6.dp))
                        Tag("NEW", Aero.Cyan)
                    }
                    if (a.acknowledged) {
                        Spacer(Modifier.width(6.dp))
                        Tag("ACKNOWLEDGED", Aero.TextMuted)
                    }
                    Spacer(Modifier.weight(1f))
                    Text(a.timestamp, style = MaterialTheme.typography.labelSmall, color = Aero.TextFaint)
                }
                Spacer(Modifier.height(8.dp))
                Text(a.title, style = MaterialTheme.typography.titleMedium, color = Aero.Text)
                Text("${a.aircraftId}, ${a.component}", style = MaterialTheme.typography.bodyMedium, color = Aero.Cyan)
                Spacer(Modifier.height(10.dp))
                Text("AI explanation", style = MaterialTheme.typography.labelMedium, color = Aero.TextMuted)
                Text(
                    a.explanation,
                    style = MaterialTheme.typography.bodyMedium,
                    color = Aero.Text,
                    maxLines = if (expanded) Int.MAX_VALUE else 2,
                    overflow = TextOverflow.Ellipsis,
                )
                Spacer(Modifier.height(8.dp))
                Text("Recommended action", style = MaterialTheme.typography.labelMedium, color = Aero.TextMuted)
                Text(a.recommendedAction, style = MaterialTheme.typography.bodyMedium, color = color)
                if (expanded) {
                    Spacer(Modifier.height(12.dp))
                    Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                        SecondaryButton(
                            if (a.acknowledged) "Acknowledged" else "Acknowledge",
                            onClick = onAcknowledge,
                            enabled = !a.acknowledged,
                            icon = Icons.Filled.Check,
                            modifier = Modifier.weight(1f),
                        )
                        SecondaryButton("Aircraft", onClick = onOpenAircraft, icon = Icons.Filled.Flight, modifier = Modifier.weight(1f))
                    }
                } else {
                    Spacer(Modifier.height(4.dp))
                    Text("Tap for details and actions", style = MaterialTheme.typography.labelSmall, color = Aero.TextFaint)
                }
            }
        }
    }
}
