package com.aeromaintenance.ai.ui.screens;

import android.text.TextUtils;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.TextView;

import com.aeromaintenance.ai.AppState;
import com.aeromaintenance.ai.Destination;
import com.aeromaintenance.ai.MainActivity;
import com.aeromaintenance.ai.R;
import com.aeromaintenance.ai.data.Alert;
import com.aeromaintenance.ai.data.Severity;
import com.aeromaintenance.ai.ui.Palette;
import com.aeromaintenance.ai.ui.Type;
import com.aeromaintenance.ai.ui.Ui;
import com.aeromaintenance.ai.ui.widget.ButtonView;
import com.aeromaintenance.ai.ui.widget.PanelView;

import java.util.ArrayList;
import java.util.List;

/**
 * Alerts raised by the AI, each with timestamp, aircraft, component, severity,
 * AI-generated explanation and recommended action.
 */
public class AlertsScreen extends BaseScreen {

    /** Null = all severities. */
    private Severity filter;

    public AlertsScreen(MainActivity activity) {
        super(activity);
    }

    @Override
    protected boolean rendersOn(AppState.Change change) {
        return change == AppState.Change.ALERTS;
    }

    @Override
    protected void build() {
        List<Alert> all = state.alerts();
        List<View> pills = new ArrayList<>();
        pills.add(Ui.filterPill(ctx, "All " + all.size(), filter == null, Palette.CYAN, v -> setFilter(null)));
        for (final Severity s : Severity.values()) {
            int n = 0;
            for (Alert a : all) {
                if (a.severity == s) n++;
            }
            pills.add(Ui.filterPill(ctx, s.title() + " " + n, filter == s, Palette.severity(s), v -> setFilter(s)));
        }
        add(Ui.pillRow(ctx, pills));

        List<Alert> shown = new ArrayList<>();
        for (Alert a : all) {
            if (filter == null || a.severity == filter) shown.add(a);
        }
        if (shown.isEmpty()) {
            add(Ui.text(ctx, "No alerts at this severity. Run an AI analysis on abnormal data to raise one.",
                    Type.Style.BODY_MEDIUM, Palette.TEXT_MUTED));
        }
        String newestId = all.isEmpty() ? null : all.get(0).id;
        for (Alert a : shown) {
            boolean highlight = isFocused("alert") && a.isNew && a.id.equals(newestId);
            View card = alertCard(a, a.id.equals(state.expandedAlertId()), highlight);
            if (a.id.equals(newestId)) focusTarget("alert", card);
            add(card);
        }
        add(Ui.prototypeNote(ctx, "Alerts are generated by the prototype from simulated telemetry. Explanations are "
                + "produced from the analysis features, not written by hand."));
    }

    private void setFilter(Severity s) {
        filter = s;
        render();
    }

    private View alertCard(final Alert a, final boolean expanded, boolean highlight) {
        int color = Palette.severity(a.severity);
        PanelView panel = new PanelView(ctx, 0);
        panel.setHighlighted(highlight);
        panel.onTap(v -> state.setExpandedAlert(expanded ? null : a.id));
        // Clip the coloured strip to the rounded corners.
        panel.setClipToOutline(true);

        LinearLayout row = new LinearLayout(ctx);
        View strip = new View(ctx);
        strip.setBackgroundColor(a.acknowledged ? Palette.HAIRLINE : color);
        row.addView(strip, new LinearLayout.LayoutParams(dp(5), ViewGroup.LayoutParams.MATCH_PARENT));

        LinearLayout col = Ui.column(ctx);
        col.setPadding(dp(14), dp(14), dp(14), dp(14));
        LinearLayout tags = Ui.row(ctx);
        tags.addView(Ui.tag(ctx, a.severity.label, color, !a.acknowledged));
        if (a.isNew) {
            tags.addView(Ui.hspace(ctx, 6));
            tags.addView(Ui.tag(ctx, "NEW", Palette.CYAN));
        }
        if (a.acknowledged) {
            tags.addView(Ui.hspace(ctx, 6));
            tags.addView(Ui.tag(ctx, "ACKNOWLEDGED", Palette.TEXT_MUTED));
        }
        tags.addView(Ui.fill(ctx));
        tags.addView(Ui.text(ctx, a.timestamp, Type.Style.LABEL_SMALL, Palette.TEXT_FAINT));
        col.addView(tags, Ui.matchWrap());

        Ui.add(col, Ui.text(ctx, a.title, Type.Style.TITLE_MEDIUM, Palette.TEXT), 8);
        col.addView(Ui.text(ctx, a.aircraftId + ", " + a.component, Type.Style.BODY_MEDIUM, Palette.CYAN));
        Ui.add(col, Ui.text(ctx, "AI explanation", Type.Style.LABEL_MEDIUM, Palette.TEXT_MUTED), 10);
        TextView explanation = Ui.text(ctx, a.explanation, Type.Style.BODY_MEDIUM, Palette.TEXT);
        if (!expanded) {
            explanation.setMaxLines(2);
            explanation.setEllipsize(TextUtils.TruncateAt.END);
        }
        col.addView(explanation);
        Ui.add(col, Ui.text(ctx, "Recommended action", Type.Style.LABEL_MEDIUM, Palette.TEXT_MUTED), 8);
        col.addView(Ui.text(ctx, a.recommendedAction, Type.Style.BODY_MEDIUM, color));
        if (expanded) {
            ButtonView ack = Ui.secondary(ctx, a.acknowledged ? "Acknowledged" : "Acknowledge", R.drawable.ic_check,
                    v -> state.acknowledge(a.id));
            ack.setEnabled(!a.acknowledged);
            View aircraft = Ui.secondary(ctx, "Aircraft", R.drawable.ic_flight, v -> {
                state.selectAircraft(a.aircraftId);
                state.navigate(Destination.detail(a.aircraftId));
            });
            Ui.add(col, Ui.equalRow(ctx, 8, ack, aircraft), 12);
        } else {
            Ui.add(col, Ui.text(ctx, "Tap for details and actions", Type.Style.LABEL_SMALL, Palette.TEXT_FAINT), 4);
        }
        row.addView(col, Ui.weight(1f));
        panel.addView(row, Ui.matchWrap());
        panel.setContentDescription(a.severity.label + " alert: " + a.title + ", " + a.aircraftId);
        return panel;
    }
}
